#ifndef ERROR_H
#define ERROR_H

#define ARG_ERR_MISSING_FILE 1
#define ARG_ERR_UNKNOWN_ARG 2
#define ARG_ERR_MULTIPLE_ARG 3
#define ARG_ERR_PORT_IS_NOT_NUMBER 4
#define ARG_ERR_TOO_MUCH_ARGS 5

#define SERVER_ERR_SOCKET_FAILED 9
#define SERVER_ERR_BIND_FAILED 10
#define SERVER_ERR_LISTEN 11
#define SERVER_ERR_ACCEPT_FAILED 12
#define SERVER_ERR_FORK_FAILED 13
#define SERVER_ERR_SETSOCKOPT 14
#define SERVER_ERR_SEND_FAILED 15
#define SERVER_ERR_ENCODE_DECODE_FAILED 16   

#define DATABASE_ERR_OPEN_FILE_FAILED 20
#define DATABASE_ERR_FILTER_SUBSTRING 21
#define DATABASE_ERR_FILTER_COLUMN 22

#define INTERNAL_ERR 99

void printError(int errorCode);

#endif